# --- Gemini API Key ---
GEMINI_API_KEY = "AIzaSyBbQoe62X292WFbRHf6ITA6uQZAWqqs_SM"

# --- Server Configuration ---
[server]
headless = true

# --- Firebase Admin SDK Credentials ---
# These should be copied directly from your Firebase service account JSON key file.
[firebase_credentials]
type = "service_account"
project_id = "prepbuddy-d9e0d"
private_key_id = "83edb87641e2634feb150bc50c60c20ae0a2e106"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC1l3SfTuUBm2je\n1AmaMFBgwnaWhyIGVpzpnQRFKq59pIKUvORLWlPVxuFMl1V0ymryEtIFGhdOigu6\nO0HB6i6pfR7bNDztgAmGs5rc63E/o2BgIvESgV1ddJmymDNtf7KZ2R4ihjpu3f07\nihV/taA2aOL9vuYT8ojCE7c2Je1K7Qegjyfe3+Zduna+rVZGbov8UKnxQ6ywy7LJ\nDon4iNOgtXWjHRA0VEXlzabl8Xb/fidGghqLsEl7KKc3QMUWCQRjun9wNmwICBRy\nPYYHtOBx6AI25IHSZo+jwZ5drCGmTPmfQpvaWDSL3PqaNUZVbkU9WtzWbHp+qiHh\nBNeVlzvZAgMBAAECggEADalFI2qFqTkqOrBIQCawF1Vt4z1rkn8/2wXeYT84pRhk\nIAE1ahNTsQafIrpUWh7TzJ4cmXho5jZVs0cbt3VRGRxh/sL3bfUm0lDO/t2CFbPq\nb1UVnosnrV0VJoXTgaJ8mt0mCpofSYGvGER3QVY2RT2fDRCoYboKbpJZ40uXZl5d\n6PxyBCqla+oVKZGpXwieAtZF+WV/LF1Y/YsKlu58jXKa2H0QT0MPboDYOc+g3LiQ\nUYl6KkKrLR+9o6I9qIr2xDjs8cTK5VZU2ZS+7DMvkvsRJzSOs6X4fOknj6MpGxpx\ngsERw/JJ1adj7ACLHP9qua3keTXznXFjsQZUVaHEgQKBgQDkPATjSmX5Z6X983WY\nRHy8uRkXyZRH40SY17i4/+ZWztbPE7dnyFiQDBFMuKnnLbi1godGlZ4mOzXQyOUD\npjr0dVz/TxCkI21YUgU6CqOhmnfpsPHpTFg99wdi6Tn82gqpFGsMzQd5iRZnLp2a\nDXEhJVKattvrAD4yEUdJ2orjWQKBgQDLrtLRNStrgEKJXMRipTeV2d61PVumufBO\nD0Rm9xytH+bg0BxisRYpXOyl81Cm/cyiOVYhcABRgtEX7O77Lg0RV8P36zaVFgej\n44r6Qg3wzJDOjR104yUc17tX87Kc7x9vlqt5ogh4tUgoqL15MyWLhQGPDGO27aj1\ndMHZ4LaMgQKBgQC7rUsLqEsQepW5rPBfJLo56i9jKySetJjc4k8I+YzshyuGnpzr\nX4jL8tBq+VLlQeiogUxB05h3sarAI+KGTLQf/z5YxyhVALjSrqeTodoKcl32scVL\nZbcORUsyn7xKWvX3MU4R+asS2pKsiF2ap0EG040IoiNXLBz4yNKJPYeGCQKBgQDL\nORI1FNTOvLkmbr2vIuOUCz6PHLpOXuUqLUd1aIdfIR5uHpbDzaar/IBNj7hf9Yjw\nLz8Fu8dFjL1tHsTPLwJw1F2+Bhx+oe1bkxO+YJuiL6knvVqvnlcQMRtGROtoc5ms\n7+sFQCstrMpjbwElZWfHjhyhCp6PDQ9wYF9uMSxSgQKBgFCYMJh6JyDlnFZUPKql\nht0l9+v8DfXngnEfcIhx2FpF+7EjG2n4XMB/UDiBoslvkuj5jaf/vNffFQs4gNxk\nanIpXPlM+cCD5iBCrZEMciR0m5i69XWzic7KZldFd+hO0WyhjaEZda+EJWv6n0km\n+xuAFYRkFJyL/1OSwnlxhcRA\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@prepbuddy-d9e0d.iam.gserviceaccount.com"
client_id = "112473561585405115841"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40prepbuddy-d9e0d.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
